version: "3.9"
services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: ecommerce_boari
      MYSQL_ROOT_HOST: "%"
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    expose:
      - 3308
    networks:
      - ecommerce-boari-network
  ecommerce-boari:
    image: nicholasboari/ecommerce-boari
    restart: always
    build: ./api
    working_dir: /ecommerce-boari-api
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: ${DATASOURCE_URL}
      SPRING.DATASOURCE.USERNAME: ${DATASOURCE_USERNAME}
      SPRING.DATASOURCE.PASSWORD: ${DATASOURCE_PASSWORD}
      SECRET_KEY_JWT: ${SECRET_KEY_JWT}
      PROFILE_TYPE: ${PROFILE_TYPE}
    ports:
      - "8090:8090"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - ecommerce-boari-network
networks:
  ecommerce-boari-network:
    driver: bridge
