version: "3.9"
services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: ecommerce_boari
      MYSQL_ROOT_HOST: "%"
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    expose:
      - 3308
    networks:
      - ecommerce-boari-network
  api:
    image: ecommerce-boari:latest
    restart: always
    build: ./api
    working_dir: /ecommerce-boari
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:h2:mem:testdb
      SPRING.DATASOURCE.USERNAME: sa
      SPRING.DATASOURCE.PASSWORD:
      SECRET_KEY_JWT: ${SECRET_KEY_JWT:-R2fCTQLWf1MH8mhl/7VibY7YuKEZ89PuQm2fk31/EWKWSi0Xi0Qu1fVkAk1trJKO}
      PROFILE_TYPE: ${PROFILE_TYPE:-test}
    ports:
      - "8090:8090"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - ecommerce-boari-network
networks:
  ecommerce-boari-network:
    driver: bridge
