spring:
  config:
    import: optional:secrets.properties
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

aws:
  accessKey: ${ACCESS_KEY}
  secretKey: ${SECRET_KEY}
  region: ${REGION}
  s3:
    mock: true
    buckets:
      customer: ${CUSTOMER_S3}
