--INSERT INTO tb_category (name, image_Url) VALUES ('Category 1', 'image1.jpg');
--INSERT INTO tb_category (name, image_Url) VALUES ('Category 2', 'image2.jpg');
--INSERT INTO tb_category (name, image_Url) VALUES ('Category 3', 'image3.jpg');
