name: Continuous-Integration with Github Actions

on:
  push:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Application Jar
      working-directory: ./ecommerce-boari-api/api
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: ./ecommerce-boari-api
      run: docker-compose up 
      
    - name: Push to Docker Hub Container Registry
      run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/ecommerce-boari:latest ${{ secrets.DOCKER_USERNAME }}/ecommerce-boari:${{ github.run_id }} 
          
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-boari:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-boari:latest
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
